platform :ios, '10.0'
use_frameworks!
target 'BoApps' do
pod 'Alamofire', '~> 4.3'
pod 'DynamicColor', '~> 3.1'
pod 'AlamofireImage', '~> 3.2'
pod 'SWXMLHash', '~> 3.0.0'
pod 'IQKeyboardManagerSwift','~> 4.0.6'
pod 'XCDYouTubeKit', '~> 2.5'
pod 'FMDB', '~> 2.6'
pod 'KCFloatingActionButton', '~> 2.1'

end
